# Generated by Django 4.0.3 on 2022-03-23 18:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LoanApplicant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, unique=True)),
                ('nationality', models.CharField(max_length=20, null=True)),
                ('dob', models.DateField(null=True)),
                ('gender', models.CharField(max_length=20, null=True)),
                ('martial', models.CharField(max_length=20, null=True)),
                ('type', models.CharField(max_length=20, null=True)),
                ('id_type', models.CharField(max_length=20, null=True)),
                ('id_no', models.IntegerField(null=True)),
                ('address', models.CharField(max_length=20, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('home_no', models.IntegerField(null=True)),
                ('mobile', models.IntegerField(null=True)),
            ],
            options={
                'verbose_name_plural': 'LoanApplicant',
            },
        ),
        migrations.CreateModel(
            name='LoanApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_num', models.IntegerField(unique=True)),
                ('application_date', models.DateField()),
                ('application_type', models.CharField(choices=[('Personal', 'Personal'), ('Vehicle', 'Vehicle'), ('Home', 'Home'), ('Education', 'Education')], max_length=50)),
                ('finance_amount', models.IntegerField()),
                ('finance_period', models.IntegerField()),
                ('interest_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('loan_status', models.CharField(choices=[('Approved', 'Approved'), ('Processing', 'Processing'), ('Rejected', 'Rejected')], max_length=40)),
                ('existing_applicant', models.BooleanField()),
                ('applicant_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loanapp.loanapplicant')),
            ],
            options={
                'verbose_name_plural': 'LoanApplication',
            },
        ),
    ]
